# Generated by Django 3.1.4 on 2021-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='upload',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
