# Generated by Django 3.1.4 on 2021-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='upload',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
