# Generated by Django 3.1.4 on 2021-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20210111_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='upload',
            field=models.ImageField(upload_to='images'),
        ),
    ]
