# Generated by Django 3.1.4 on 2021-01-11 16:44

from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20210111_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=tutorials.models.upload_path),
        ),
    ]
