# Generated by Django 3.1.4 on 2021-01-11 17:23

from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20210111_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='x',
            field=models.ImageField(blank=True, null=True, upload_to=tutorials.models.upload_path),
        ),
    ]
