# Generated by Django 3.1.4 on 2021-01-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_tutorial_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='x',
        ),
    ]
